[phases.setup]
nixPkgs = ["nodejs-20_x", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "cd frontend && npm install --legacy-peer-deps",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "cp -r frontend/dist/* backend/src/static/"
]

[start]
cmd = "cd backend && python src/main.py"