[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs", "gcc"]

[phases.install]
cmds = [
    "npm install",
    "python -m pip install -r requirements.txt"
]

[phases.build] 
cmds = [
    "npm run build"
]

[start]
cmd = "cd backend && python -m gunicorn --bind 0.0.0.0:$PORT src.main:app"