[phases.setup]
nixPkgs = ["...", "python311", "gcc"]

[phases.install]
cmds = [
    "npm install",
    "pip install -r requirements.txt"
]

[phases.build] 
cmds = [
    "npm run build"
]

[start]
cmd = "cd backend && gunicorn --bind 0.0.0.0:$PORT src.main:app"