[phases.setup]
nixPkgs = ["nodejs-18_x", "python3", "python3Packages.pip"]

[phases.install]
cmds = [
    "cd frontend && npm ci",
    "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "cp -r frontend/dist/* backend/src/static/"
]

[start]
cmd = "cd backend && python src/main.py"